
//Rack stuff
export const PLAY_RACK_LETTER = 'PLAY_RACK_LETTER'
export const RETURN_RACK_LETTERS = 'RETURN_RACK_LETTERS'

// Board stuff
export const INITIALIZE_BOARD_SQUARES = "INITIALIZE_BOARD_SQUARES"
export const UPDATE_ACTIVE_SQUARE = 'UPDATE_ACTIVE_SQUARE'

export const SQUARE_CLICKED = "SQUARE_CLICKED"
export const SQUARE_KEYPRESS = "SQUARE_KEYPRESS"