
//Rack stuff
export const PLAY_RACK_LETTER = 'PLAY_RACK_LETTER'
export const RETURN_RACK_LETTERS = 'RETURN_RACK_LETTERS'

// Board stuff
export const INITIALIZE_BOARD_SQUARES = "INITIALIZE_BOARD_SQUARES"
export const UPDATE_ACTIVE_SQUARE = 'UPDATE_ACTIVE_SQUARE'

// Square stuff 
export const SQUARE_MOUSEUP = "SQUARE_MOUSEUP"
export const SQUARE_KEYDOWN = "SQUARE_KEYDOWN"
export const SQUARE_MOUSEDOWN = "SQUARE_MOUSEDOWN"

// PlayerDisplay stuff
export const SHUFFLE_LETTERS = "SHUFFLE_LETTERS"
export const RETURN_LETTERS = "RETURN_LETTERS"
export const EXCHANGE_LETTERS = "EXCHANGE_TILES"
export const PLAY_TILES = "PLAY_TILES"
export const PASS_TURN = "PASS_TURN"
export const CHALLENGE_TURN = "CHALLENGE_TURN"
export const FORFEIT_GAME = "FORFEIT_GAME"