
//Rack stuff
export const PLAY_RACK_LETTER = 'PLAY_RACK_LETTER'
export const RETURN_RACK_LETTERS = 'RETURN_RACK_LETTERS'

// Board stuff
export const INITIALIZE_BOARD_SQUARES = "INITIALIZE_BOARD_SQUARES"
export const UPDATE_ACTIVE_SQUARE = 'UPDATE_ACTIVE_SQUARE'

// Square stuff 
export const SQUARE_CLICKED = "SQUARE_CLICKED"
export const SQUARE_KEYPRESS = "SQUARE_KEYPRESS"

// PlayerDisplay stuff
export const SHUFFLE_LETTERS = "SHUFFLE_LETTERS"
export const PLAY_TILES = "PLAY_TILES"
export const RETURN_TILES = "RETURN_TILES"
export const EXCHANGE_LETTERS = "EXCHANGE_TILES"
export const PASS_TURN = "PASS_TURN"
export const CHALLENGE_TURN = "CHALLENGE_TURN"
export const FORFEIT_GAME = "FORFEIT_GAME"