//Game stuff
export const UPDATE_NAME = "UPDATE_NAME"
export const UPDATE_GAME_ID = "UPDATE_GAME_ID"
export const JOIN_GAME = "JOIN_GAME"
export const CREATE_GAME = "CREATE_GAME"
export const INPUT_KEYDOWN = "INPUT_KEYDOWN"

//Rack stuff
export const PLAY_RACK_LETTER = 'PLAY_RACK_LETTER'
export const RETURN_PLAYED_LETTER = 'RETURN_PLAYED_LETTER'
export const RETURN_PLAYED_LETTERS = 'RETURN_PLAYED_LETTERS'
export const RETURN_EXCHANGED_LETTER = 'RETURN_EXCHANGED_LETTER'
export const RETURN_EXCHANGED_LETTERS = 'RETURN_EXCHANGED_LETTERS'

//Exchange stuff
export const EXCHANGE_KEYDOWN = "EXCHANGE_KEYDOWN"
export const EXCHANGE_ONCLICK = "EXCHANGE_LETTER_ONCLICK"

//PlayerActions stuff
export const SHUFFLE_LETTERS = "SHUFFLE_LETTERS"
export const RETURN_LETTERS = "RETURN_LETTERS"
export const EXCHANGE_LETTERS = "EXCHANGE_LETTERS"
export const PLAY_TILES = "PLAY_TILES"
export const PASS_TURN = "PASS_TURN"
export const CHALLENGE_TURN = "CHALLENGE_TURN"

//GameInfo
export const FORFEIT_GAME = "FORFEIT_GAME"

// Board stuff
export const INITIALIZE_BOARD_SQUARES = "INITIALIZE_BOARD_SQUARES"

// Square stuff 
export const SQUARE_MOUSEUP = "SQUARE_MOUSEUP"
export const SQUARE_KEYDOWN = "SQUARE_KEYDOWN"
export const SQUARE_MOUSEDOWN = "SQUARE_MOUSEDOWN"


