//Actions for AJAX requests to scrabble service
export const ASYNC_GAME_UNKNOWN_REQUEST = "GAME_UKNOWN_REQUEST"
export const ASYNC_GAME_UNKNOWN_SUCCESS = "GAME_UKNOWN_SUCCESS"
export const ASYNC_GAME_UNKNOWN_FAILURE = "GAME_UKNOWN_FAILURE"

export const ASYNC_GAME_PENDING_REQUEST = "GAME_PENDING_REQUEST"
export const ASYNC_GAME_PENDING_SUCCESS = "GAME_PENDING_SUCCESS"
export const ASYNC_GAME_PENDING_FAILURE = "GAME_PENDING_FAILURE"