//Actions for AJAX requests to scrabble service
export const ASYNC_CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST"
export const ASYNC_CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS"
export const ASYNC_CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE"

export const ASYNC_JOIN_GAME_REQUEST = "JOIN_GAME_REQUEST"
export const ASYNC_JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS"
export const ASYNC_JOIN_GAME_FAILURE = "JOIN_GAME_FAILURE"