//Game stuff
export const UPDATE_NAME = "UPDATE_NAME"
export const UPDATE_GAME_ID = "UPDATE_GAME_ID"
export const JOIN_GAME = "JOIN_GAME"
export const CREATE_GAME = "CREATE_GAME"
export const START_GAME = "START_GAME"
export const REFRESH_GAME = "REFRESH_GAME"
export const INPUT_KEYDOWN = "INPUT_KEYDOWN"

//Rack stuff
export const PLAY_RACK_TILE = 'PLAY_RACK_TILE'
export const RETURN_PLAYED_TILE = 'RETURN_PLAYED_TILE'
export const RETURN_PLAYED_TILES = 'RETURN_PLAYED_TILES'
export const RETURN_EXCHANGED_TILE = 'RETURN_EXCHANGED_TILE'
export const RETURN_EXCHANGED_TILES = 'RETURN_EXCHANGED_TILES'

//Exchange stuff
export const EXCHANGE_KEYDOWN = "EXCHANGE_KEYDOWN"
export const EXCHANGE_ONCLICK = "EXCHANGE_LETTER_ONCLICK"

//PlayerActions stuff
export const SHUFFLE_TILES = "SHUFFLE_TILES"
export const RETURN_TILES = "RETURN_TILES"
export const EXCHANGE_TILES = "EXCHANGE_TILES"
export const PLAY_TILES = "PLAY_TILES"
export const PASS_TURN = "PASS_TURN"
export const CHALLENGE_TURN = "CHALLENGE_TURN"

//GameInfo
export const LEAVE_GAME = "LEAVE_GAME"
export const FORFEIT_GAME = "FORFEIT_GAME"
export const NEW_GAME = "NEW_GAME"

// Square stuff 
export const SQUARE_MOUSEUP = "SQUARE_MOUSEUP"
export const SQUARE_KEYDOWN = "SQUARE_KEYDOWN"
export const SQUARE_MOUSEDOWN = "SQUARE_MOUSEDOWN"


